//首页控制器
app.controller('orderPayController',function($scope,loginService){
	$scope.showName=function(){
			loginService.showName().success(
					function(response){
						$scope.loginName=response.loginName;
					}
			);
	}
});